name: Article Publish
on:
  push:
    branches: ["main"]
permissions:
  contents: write
  pull-requests: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/submit.yml@v1
    with:
      id-pattern-regex: "^ubcgif-(?:[a-zA-Z0-9-_]{3,40})$"
      venue: gif-consortium
      kind: tutorial
      collection: aqgeo
      publish: true
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
